version: '3'
services:
  mysql:
    image: percona:8.0.20-11-centos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'testpassword'
      MYSQL_DATABASE: arbiter_data
    volumes:
      - ./conf:/usr/local/mysqlconf
    ports:
      - "3306"
    entrypoint:
      bash -c "
      cp /usr/local/mysqlconf/*.cnf /etc/my.cnf.d/
      && chmod 644 /etc/my.cnf.d/*.cnf 
      && /docker-entrypoint.sh mysqld
      "
  migrate_schemas:
    build:
      context: ./migrations
    depends_on:
      - mysql
    volumes:
      - ./migrations:/migrations
    entrypoint: sh ./wait-for -t 60 mysql:3306 -- /migrate -path=/migrations/ -database mysql://root:testpassword@tcp(mysql:3306)/arbiter_data goto 60
