version: '3'
services:
  mysql:
    image: percona:8.0-centos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'testpassword'
      MYSQL_DATABASE: arbiter_data
    volumes:
      - ./conf:/etc/my.cnf.d:ro
    ports:
      - "3306"
  migrate_schemas:
    build:
      context: ./migrations
    depends_on:
      - mysql
    volumes:
      - ./migrations:/migrations
    entrypoint: sh ./wait-for -t 60 mysql:3306 -- /migrate -path=/migrations/ -database mysql://root:testpassword@tcp(mysql:3306)/arbiter_data up
