ALTER TABLE arbiter_data.permissions CHANGE COLUMN object_type object_type ENUM('sites', 'aggregates', 'cdf_forecasts', 'forecasts', 'observations', 'users', 'roles', 'permissions') NOT NULL;
DROP TABLE report_values;
DROP TABLE reports;
DROP PROCEDURE list_reports;
DROP PROCEDURE read_report;
DROP PROCEDURE read_report_values;
DROP PROCEDURE store_report;
DROP PROCEDURE store_report_values;
DROP PROCEDURE delete_report;
DROP PROCEDURE set_report_status;
DROP PROCEDURE set_report_metrics;
DROP TRIGGER add_object_perm_on_report_permissions_insert;
DROP TRIGGER remove_report_values_on_observation_delete;
DROP TRIGGER remove_report_values_on_forecast_delete;
DROP TRIGGER remove_report_values_on_cdf_forecast_delete;
