DROP PROCEDURE read_latest_observation_value;
DROP PROCEDURE read_latest_forecast_value;
DROP PROCEDURE read_latest_cdf_forecast_value;
DROP PROCEDURE read_observation_time_range;
DROP PROCEDURE read_forecast_time_range;
DROP PROCEDURE read_cdf_forecast_time_range;
